# Generated by Django 2.1.2 on 2018-11-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_size', models.IntegerField(default=0)),
                ('company_start_year', models.IntegerField(max_length=4)),
            ],
        ),
    ]
